### ISSUE TITLE
[MIG-559] Make MigMigration ownerReferences in DVM optional

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/mig-controller#1053]
**Describe the bug**
DVM requires a valid _MigMigration_ ownerReference set. Without it, DVM doesn't reconcile the CR. OwnerReference on MigMigration should be made optional as we move towards making DVM capable of State Only transfer. 

**To Reproduce**
Create DVM using `oc` command which doesn't have `metadata.ownerReferences` set. 

**Expected behavior**
The DVM should be reconciled assuming that it was created stand-alone and it's not part of a _MigMigration_.

**Screenshots & Snippets**

**Additional context**

**Comment by sseago** [comment]
Related to this (as discussed on slack), we need to check for nil here and return a nil migmigration if the DIM is nil:
https://github.com/konveyor/mig-controller/blob/master/pkg/apis/migration/v1alpha1/directimagestreammigration_types.go#L106
