### ISSUE TITLE
DirectVolumeMigration goes to next step even though namespace isn't created

### ISSUE THREAD

**Issue by wedsouza** [konveyor/mig-controller#1126]
**Describe the bug**
This is created to fix a bug when attempting staging step from source to destination. It was observed that the during CreateDestinationPVCs step , the logs reported namespaces "example" not found.

Release version : 1.4.4

**Proposed Fix**
Adding return err when an error occurs creating the namespace : https://github.com/konveyor/mig-controller/blob/release-1.4.4/pkg/controller/directvolumemigration/task.go#L232

**Comment by eriknelson** [comment]
Hi @wedsouza, thank you for submitting. I've cloned this to our bugzilla where we do our primary bugtracking to ensure this makes it into a downstream release and is verified by QE teams. We'll be taking a look at this shortly:

https://bugzilla.redhat.com/show_bug.cgi?id=1972903

I recommend following that bug to get email updates.

**Comment by pranavgaikwad** [comment]
@wedsouza Are you able to consistently reproduce this issue? From the code, I am not sure whether such a scenario is possible. Any error trying to create a destination namespace is returned here: https://github.com/konveyor/mig-controller/blob/11d1a981dbf81234abe0a218defd5abbeb48089f/pkg/controller/directvolumemigration/namespace.go#L48

Is there a possibility that the destination namespace was manipulated during the migration?

**Comment by wedsouza** [comment]
@pranavgaikwad it was randomly throwing error on different namespaces. The cluster we were testing on wasn't very healthy, it was throwing timeouts randomly. So it might have caused problem when trying to create the namespace on destination cluster.
Also we retried the same migration again and it threw error on another namespace.

**Comment by pranavgaikwad** [comment]
@wedsouza thanks for the information. I believe the fix I posted here #1133 should fix the issue. There definitely was a missing return statement that we fixed.

**Comment by wedsouza** [comment]
@pranavgaikwad think its needed to return err [here](https://github.com/konveyor/mig-controller/blob/master/pkg/controller/directimagemigration/task.go#L166) as well ? similar kind of error may occur

**Comment by pranavgaikwad** [comment]
@wedsouza great catch! thanks. you're right. image migration needs that fix as well

**Comment by pranavgaikwad** [comment]
@wedsouza closing this issue through #1133
