### ISSUE TITLE
Memory consumption should be reduced

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#123]
mig-controller memory usage has grown significantly. Memory consumption **does level off** eventually.

In the chart below you can see controller memory usage over period of several minutes, peaking at 224.36 MiB.

![image](https://user-images.githubusercontent.com/7576968/58587126-974aa680-822a-11e9-8832-2fb416b1b3e0.png)

**Comment by pranavgaikwad** [comment]
I am facing similar issue where the controller gets killed with `OOMKilled` status very often. I have deployed the controller on an OCP3 cluster with memory limits set to 300 Mi.

**Comment by djwhatle** [comment]
@pranavgaikwad and I discussed this further as I was troubleshooting an issue in his environment, and we realized that he had 3 `MigClusters` instead of the typical 2 you'd need to run a Migration. 

Since memory usage seems to scale _~linearly_ with each remote watch manager / controller that we create, I suspect this is why Pranav saw this issue. I'm not discrediting that memory consumption is still something that we should address.

**Comment by djwhatle** [comment]
Another occurrence of memory over consumption, @fbladilo was attempting to run a migration from OCP3->4 on a pair of clusters about ~40 days old. 

We saw memory consumption exceed a new limit of 600 MB, and cause repeated `OOMKilled` pod death. I regularly saw memory usage climb to a range of ~500-600MB just while starting up.

Also tried checking out commit c985470, which was where mig-controller was before seeing this issue. No significant change, still seeing the remotewatch against the remote cluster take a _very_ long time to start up completely.

**Comment by djwhatle** [comment]
Still happening on 4.1.

**Comment by jortel** [comment]
Memory profile data generated by `pprof`.

[controller-memory.pdf](https://github.com/fusor/mig-controller/files/3386749/controller-memory.pdf)

```
      flat  flat%   sum%        cum   cum%
15022.68kB 30.88% 30.88% 15022.68kB 30.88%  github.com/fusor/mig-controller/vendor/github.com/beorn7/perks/quantile.newStream (inline)
12340.09kB 25.36% 56.24% 12340.09kB 25.36%  encoding/base64.(*Encoding).DecodeString
 4096.65kB  8.42% 64.66%  4096.65kB  8.42%  github.com/fusor/mig-controller/vendor/github.com/json-iterator/go.(*Iterator).ReadString
 2799.57kB  5.75% 70.42%  2799.57kB  5.75%  reflect.unsafe_NewArray
 2563.06kB  5.27% 75.69%  2563.06kB  5.27%  github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/api/meta.(*DefaultRESTMapper).AddSpecific
 2560.77kB  5.26% 80.95%  2560.77kB  5.26%  reflect.mapassign
 2054.13kB  4.22% 85.17% 17076.81kB 35.10%  github.com/fusor/mig-controller/vendor/github.com/prometheus/client_golang/prometheus.newSummary
```

**Comment by dymurray** [comment]
Let's keep an eye on memory consumption as we test with more migclusters added to the controller since this grows the resource watch count. Keeping this targeted for 4.3.

**Comment by dymurray** [comment]
Closing as this is no longer an issue.

**Comment by djwhatle** [comment]
We are looking at addressing this in an upcoming release, possibly 1.4.0

**Comment by djwhatle** [comment]
Filed a new issue for implementing a pprof memory profiling switch in mig-operator: https://github.com/konveyor/mig-controller/issues/652
