### ISSUE TITLE
When setting the openshift.io/migration-registry annotation, if there's more than one service we should return an error (or fail validation on the plan when calling ensureRegistry)

### ISSUE THREAD

**Issue by sseago** [konveyor/mig-controller#155]
When setting the openshift.io/migration-registry annotation, if there's more than one service we should return an error (or fail validation on the plan when calling ensureRegistry). Currently if there happen to be two services associated with the plan (possibly due to an improper prior resource cleanup) we just set an annotation matching the first one found, which may be the wrong one.

**Comment by dymurray** [comment]
@sseago Please confirm this is still an open bug and whether aligning this to 4.3 makes sense.

**Comment by dymurray** [comment]
@sseago Please confirm this is fixed and if so close it.

**Comment by sseago** [comment]
This is still unchanged. It looks like we're following the same pattern for others as well (GetBSL, GetVSL, GetRegistryDC, etc.) -- we grab the first in the list if more than one match. I think the expectation is we should never have more than one match, and the assumption seems to be "any match should be equally good" -- I think the issue is if there are more than one, there's a good chance at least one isn't functional as it's leftover from something else. It might be an easy fix of returning an error any time there are multiple matches for BSL, RegistryService, etc., but if we start returning errors, we'll need to make sure the response actually makes sense. I imagine the outcome would be everything would start failing with the expected "duplicate <foo>" error response, and the user would need to manually delete all of the registry/BSL/etc. resources and have the controller recreate.

**Comment by djwhatle** [comment]
It appears this has been fixed. We query for the registry deployment using a UID 
https://github.com/konveyor/mig-controller/blob/505889a9f5241d9c24b4763c843eda5f08cfdefe/pkg/apis/migration/v1alpha1/migplan_types.go#L434-L441

**Comment by djwhatle** [comment]
Resolved by #712
