### ISSUE TITLE
Recovery workflows after migration failures

### ISSUE THREAD

**Issue by sseago** [konveyor/mig-controller#157]
We now have basic failure handling in place to properly set Migration state if something goes wrong during backup or restore. Longer-term, we need some sort of recovery workflow. After a failure, in some cases a simple retry is all a user might need (especially if it's on backup). In other cases, we may need to clean up from the failure (remove destination namespaces, un-do quiesce actions on the source) before allowing the user to re-run another stage and then a final migration.

**Comment by dymurray** [comment]
Adding GA Blocker label. We need the ability to reverse the quiesce behavior after a migration has run. We should explore as much as we can of recovering from failed migrations and rolling back successful migrations before GA.

**Comment by sseago** [comment]
One component of this, reversing the quiesce action, might make sense to have exposed as a standalone function, but it also fits within the recovery workflow framework.

A couple thoughts on the implementation:
To do this, we could set an annotation (something like "openshift.io/quiesced") where the value will be whatever replicas was before we set it to 0 (for everything other than DaemonSet -- for DaemonSet the presence of the annotation is all we'll need). The "reverse quiesce" function would be to do the same iteration over resources we did for quiesce, but looking for this annotation and, when we find it, re-setting replicas (removing the custom nodeSelector key for DaemonSet) and removing the annotation. I"m not sure where we'd attach the function call for this though.
￼

**Comment by dymurray** [comment]
Let's itemize this issue since this covers all functionality required by adding a "rollback" feature to the migration tool. Adding the Post 4.3 label since some of this may fall into post 4.3 buckets and some may be delivered prior to 4.3.
