### ISSUE TITLE
Integrate with new approach for cluster wide proxy in OCP 4.2

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-controller#184]
https://jira.coreos.com/browse/PROD-615

https://docs.google.com/document/d/12bBF7GTgscW8B3apVU2WagtQpWh-PWk2tOWiD0dsdfU/edit#

**Comment by dymurray** [comment]
This is an investigation/design task to learn how the cluster wide proxy is used in OCP 4.2 and determine what work is needed from the migration tool to work with it.

**Comment by djwhatle** [comment]
@eriknelson I believe you did the work on this right? Can we close this issue out?

**Comment by eriknelson** [comment]
@djwhatle yep, this was implemented in the operator and controller
