### ISSUE TITLE
Migrate PVCs that aren't attached to running pods

### ISSUE THREAD

**Issue by sseago** [konveyor/mig-controller#204]
Current stage migration behavior only migrates PVCs associated with running pods. The restic implementation currently used makes use of the existing pods, redefined on restore as dummy pods. Longer-term, should we be migrating PVCs which are bound to PVs but aren't associated with currently-running pods? Will any of these have data we care about? In addition to unconnected PVCs, there are also the cases where their pods are currently shut down, either deliberately, or due to a recent pod crash.

Doing this might require spawning temporary migration-only pods. Any concerns here other than the implementation challenges? Is this desirable in the first place?

**Comment by jwmatthews** [comment]
Related https://bugzilla.redhat.com/show_bug.cgi?id=1763832

**Comment by Danil-Grigorev** [comment]
@sseago This is possible situation for a `CronJob` created pods. If any of containers are using volume mount, it could store data in this volume. But as the job is finished, the pod will be removed, while PVC could still remain.

**Comment by jwmatthews** [comment]
In JIRA at https://issues.redhat.com/browse/MIG-179

**Comment by djwhatle** [comment]
@sseago any work remaining on this issue?

**Comment by sseago** [comment]
This is done now.
