### ISSUE TITLE
nginx deployment pod fails after move migration

### ISSUE THREAD

**Issue by rpattath** [konveyor/mig-controller#205]
After performing a move operation during migration noticed the following 

root@ip-172-31-61-189: ~/go/src/github.com/fusor/mig-operator # oc logs pods/nginx-deployment-669d967995-z2bvg -n nginx-example
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2019/07/18 14:40:13 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)
root@ip-172-31-61-189: ~/go/src/github.com/fusor/mig-operator # oc get pv
NAME   CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                      STORAGECLASS   REASON   AGE
pv9    100Gi      RWO,ROX,RWX    Retain           Bound    nginx-example/nginx-logs                           5m16s

**Comment by rpattath** [comment]
I hit this issue while testing EBS -> NFS copy migration as well.

**Comment by djwhatle** [comment]
I believe this has been resolved by https://github.com/konveyor/openshift-migration-plugin/pull/8
