### ISSUE TITLE
Go back to using GenerateName for VSL creation once upstream Velero bug is fixed

### ISSUE THREAD

**Issue by sseago** [konveyor/mig-controller#289]
In https://github.com/fusor/mig-controller/pull/288 we've stopped using generateName to create VSLs since, for now, the corresponding VSLs must have the same name on both src and dest clusters.

Once https://github.com/heptio/velero/issues/1785 is resolved upstream and we have the fix in our velero fork, we can return to the prior name generation method, along with adding the appropriate VSL reference on the Velero Restore CR.

**Comment by djwhatle** [comment]
It appears that we are using the planUID in our VSL name. 

```
func (r *MigStorage) BuildVSL(planUID string) *velero.VolumeSnapshotLocation {
	vsl := &velero.VolumeSnapshotLocation{
		Spec: velero.VolumeSnapshotLocationSpec{},
		ObjectMeta: metav1.ObjectMeta{
			Labels:    r.GetCorrelationLabels(),
			Namespace: VeleroNamespace,
			Name:      r.Name + "-" + planUID,
		},
	}

	return vsl
}
```

@sseago is this still an issue? Closing due to staleness, but please re-open if still wanted.

**Comment by sseago** [comment]
@djwhatle The upstream issue still exists. I don't know that they've ever fixed it. However, I don't really see any compelling reason to go back to using generatename. We resolved this by using a predictable name. We should just stick with what we're doing.
