### ISSUE TITLE
CRDs not migrated along with CRs

### ISSUE THREAD

**Issue by sseago** [konveyor/mig-controller#299]
So it turns out that we're not actually migrating CRDs along with CRs. This may be a regression from prior functionality. In any case, it's been broken since at least the point in which we added PV copy support.

It appears that there are two issues:
1) When creating the final backup, `includeClusterResources` needs to be nil rather than false. Along with this change we need to explicitly exclude PVs from the final backup so that when we re-enable cluster resource inclusion we don't get PVs unless it's a stage backup
2) There seems to be a bug in Velero 1.1, possibly a regression, in which CRDs aren't being included in the backup for associated included CRs even when 1) above is addressed. I'm currently discussing this part of the issue with Velero upstream.

**Comment by sseago** [comment]
Upstream issue opened:  https://github.com/heptio/velero/issues/1830

**Comment by sseago** [comment]
WIP/draft PR on our fork is here: https://github.com/fusor/velero/pull/32

 I'm not ready to merge it yet because my hope is to get something accepted upstream and backport that solution to our fork. Next step is to rebase the fork PR against upstream master, test the build and submit it as an upstream PR.

**Comment by sseago** [comment]
Note that the linked PR (and eventual upstream fix) isn't a complete solution. A related upstream bug ( https://github.com/heptio/velero/issues/964 ) results in CRs often failing on restore because, even though CRDs are restored first, they aren't necessarily ready by the time the CR restoration occurs. The effect is that the CRD is created but the CRs are not. This can be shown by deleting the namespace containing the CRs (but leaving the CRD) and migrating again. This time the CRs are restored as expected. I don't think an upstream fix for this will be coming any time soon -- a general-purpose upstream-appropriate fix will involve quite a bit of redesign. We may be able to come up with something that meets migration needs with a plugin, although I'm not entirely sure exactly where it would go right now. Perhaps one that's applied to all resources that queries the CRD list and, if a match is found and it's not "ready", blocks until it is. There could be serious performance implications here, though, with checking/querying CRDs for each and every resource restore. Better would be to block after restoring each CRD, although this would have to be implemented either as a hack in the velero codebase in our fork or, if it's possible, a post-restore plugin, although I'm not sure the latter is even possible right now.

**Comment by djwhatle** [comment]
@sseago @dymurray what is the status of this? Do we support moving CRDs? Closing due to staleness but please re-open if needed.

**Comment by sseago** [comment]
@djwhatle Closing was the right thing. The upstream fix referenced was put in place a while back. This works fine now.
