### ISSUE TITLE
[non-admin] Controller needs to watch all namespaces for creation of mig resources

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#394]
Instead of watching the `openshift-migration` namespace for creation if mig resources, the controller should be watching all namespaces since non-admin users will be creating migration resources in their respective namespaces.

**Comment by sseago** [comment]
Are we sure this isn't already the case? I'm still using the 'mig' namespace for mig resources in my dev environment and things still work there.

**Comment by dymurray** [comment]
Closing as this will be an operator issue to open where the controller is set with env var `WATCH_NAMESPACE` to the user's non-admin namespace.
