### ISSUE TITLE
Upgrade Mig* CR API version to v1beta1 and establish a convention for API version changes

### ISSUE THREAD

**Issue by Danil-Grigorev** [konveyor/mig-controller#427]
We should follow the kubernetes convention of API version changes to release product properly. Currently the migration tooling is shipped as `v1alpha1` version for every release. We should at least move to v1beta1 to be a valuable product. 

Link: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/migrating-existing-apis.md

**Comment by djwhatle** [comment]
@Danil-Grigorev this is something I've had on my mind for a while.


According to the rules outlined in https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-versioning, moving to a `beta` API version seems suitable as you mention. 

---

**I propose that this change will come with some added requirements as we change the API:**
   - After a release of mig-controller, the first PR making an API change would need to bump the API version
   - Each developer who makes changes to the API must follow up their change with documentation 

---

@jmontleon what level of additional burden (if any) will this change introduce on the konveyor-operator side?

@jortel do you anticipate the above procedures would be painful to follow?

cc @sseago @dymurray @mansam, do you guys foresee problems or have objections to moving to a beta API?

**Comment by dymurray** [comment]
With the non-admin work I think it makes more sense to wait until that is merged as it will require at least a new CRD and may make some significant changes to the spec fields of some CRs. Would be easier to deal with schema changes while in alpha. Thoughts?

**Comment by djwhatle** [comment]
More info for learning about API version changes over time:

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md

https://book.kubebuilder.io/multiversion-tutorial/tutorial.html

**Comment by djwhatle** [comment]
This is something we will consider in the future, but our API is still evolving in breaking ways at this time.
