### ISSUE TITLE
StartRemoteWatch should preserve the same scheme as the main manager

### ISSUE THREAD

**Issue by Danil-Grigorev** [konveyor/mig-controller#437]
Right now we have a duplicate scheme for the remote watches, which could cause errors like this, if controller pod was restarted during a running migration, and the remote watches were not yet established, and migration tried to quiesce an app:

```{"level":"error","ts":1583150509.2525918,"logger":"migration|fkl8n","msg":"","migration":"28247050-5c05-11ea-b46b-5b815f8210b4","error":"no kind is registered for the type v1.DeploymentConfigList in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:61\"",...```

We need to keep it consistent, and pass an existing one from a main manager instance.

**Comment by jortel** [comment]
The manager generated by kube-builder creates the manager without a `Scheme` option. As as result, all of the managers use the global `scheme.Scheme`.

**Comment by dymurray** [comment]
Closing as Jeff has verified this isn't the case.
