### ISSUE TITLE
[MIG-399] Use go modules

### ISSUE THREAD

**Issue by gildub** [konveyor/mig-controller#438]
From golang 1.14 modules are defacto standard

**Comment by dymurray** [comment]
Let's setup an hour meeting to discuss what we learned moving the plugin repos to go modules and help the controller contributors get up to speed on this.

**Comment by djwhatle** [comment]
Closed https://github.com/konveyor/mig-controller/pull/439 due to staleness. Still plan to switch to go modules in the future.
