### ISSUE TITLE
GVK compare requires cluster-admin to function

### ISSUE THREAD

**Issue by Danil-Grigorev** [konveyor/mig-controller#451]
@eriknelson tested mig-controller in a setup when a source cluster is also a host cluster for the mig toolkit, where an RBAC issue was discovered. At the moment in such setup is using local `migration-controller` role, which is not `cluster-admin`, and it leads to issues while listing random resources on the local cluster. This issue does not occur with a remote cluster, because for communication with it, a `mig` `ServiceAccount` is used, which has the `cluster-admin` privileges. We need to unify this.

Current approach for GVK compare requires listing resources, marked as incompatible for migration in each namespace selected in the `MigPlan` resource. This means that it could potentially list every existing resource in the cluster, depending on the gap between cluster versions set for migration (1.7 -> 1.17+). 

Some investigation is needed to allow the GVK compare to run with non `cluster-admin` RBAC.

**Comment by Danil-Grigorev** [comment]
@jortel May I get any opinions how to deal with it?

**Comment by djwhatle** [comment]
Relevant: https://github.com/konveyor/mig-operator/pull/259/
