### ISSUE TITLE
ServiceInstance failing after migration from 3.9 to 3.11

### ISSUE THREAD

**Issue by thurcombe** [konveyor/mig-controller#462]
I recently migrated a number of projects from an origin 3.9 to 3.11 cluster.

Everything seemed to have gone well but I now notice that any projects created from the service catalog on the 3.9 cluster are raising events because the 3.11 cluster is presumably now  trying to provison something that already exists

`Error provisioning ServiceInstance of ClusterServiceClass (K8S: "3414d2af-5c74-11ea-9acb-566fb25c0057" ExternalName: "postgresql-persistent") at ClusterServiceBroker "template-service-broker": Status: 409; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>
`

Is this a known issue, can anyone suggest a workaround?

**Comment by djwhatle** [comment]
Hey @thurcombe, thanks for the issue report. 

According to the info you've provided, it seems that there are some problems with moving ServiceInstances around with Velero. 

My initial suspicion is that the template service broker is keeping track of whether a ServiceInstance has been reconciled in the status, which is lost during migration.

The first cut I'd take at fixing this would be to skip restoring TSB ServiceInstances. We would still migrate the on-cluster resources deployed as a result of the ServiceInstance provision.

**Comment by thurcombe** [comment]
@djwhatle is this something we can do via config? I didn't see any method for excluding ServiceInstance objects.

**Comment by djwhatle** [comment]
@thurcombe currently, we don't expose the ability to manually configure exclusion of a particular GVK (e.g. ServiceInstance), but please see info below on "pre/post hooks" for a solution to this problem in a coming release.

In a recent discussion, the team weighed the consequences of stripping ServiceInstances from the restored resources list. 

Our concerns with adding a restore exclusion for ServiceInstances are:
 - Loss of coordinates and management interface to externally provisioned services
 - Loss of service binding management capability 
 - Loss of service deprovision capability

I don't think we can make the decision for folks to destroy this information. 

---

All of this said, we are currently implementing a "pre/post hooks" feature currently which could be useful for cleaning up leftover ServiceInstances on your clusters if you deem that an acceptable path and are OK with losing the capabilities listed above on your provisioned services. The pre/post hook feature allows for running of custom ansible logic to manipulate cluster resources at various points in the restore.

It also strikes me that TSB may be flawed if a fully provisioned ServiceInstance can't be moved around without triggering a reprovision. This could be something to bring up on that project.
