### ISSUE TITLE
Add support for multiple mig-controller instances connected to a single cluster

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#47]
There are some potential use-cases where we might want to be able to connect multiple mig-controller instances to a single cluster.

- Moving content from 1 source cluster to 2 destination clusters, with the controllers running on the 2 destination clusters
- Moving contents from 2 source clusters to 1 destination cluster, with the controllers running on the 2 source clusters

In both of the above cases, we could work around the issue by installing mig-controller on the side with only 1 cluster involved (source and destination, respectively). If for some reason it was not possible to choose the side we would deploy mig-controller to, the flexibility of controller placement could come in handy.

Having the capability for the mig-controller to peacefully co-manage with another mig-controller may be possible if we were to tag all resources created on the remote cluster with some kind of unique identifier.

---
This use-case was brought up by @sseago

**Comment by sseago** [comment]
It sounds like there are 3 overall cases here:
1) one controller, one source cluster, and one dest cluster -- that's mainly what we're targeting for now
2) one controller, and either one src/multple dest or one dest/multiple src clusters -- this a "nice to have" case to handle relatively soon, probably not much extra work but we'd have to be careful about assuming namespace+name uniqueness
3) multiple controllers, and a) one src/multiple dest; multiple src/one dest; multiple src/multiple dest. I think once we get to multiple controllers, the number of src/dest clusters doesn't matter -- this is the use case described above.

**Comment by djwhatle** [comment]
This isn't something we are likely to support in the future.
