### ISSUE TITLE
Update CAM configuration for a cluster-scoped resource blacklist

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#504]
ClusterResourceQuotas are cluster scoped resources that namespace scoped resources (Pods) depend on their existence in order to be properly restored. A more common example are PersistentVolumes. Generally, a user cannot list all PVs in the cluster, but CAM requires this to help make intelligent decisions about migrating PVCs in a given namespace.

Our plan to address this is to expose a list of cluster-scoped resources as a configuration option to allow an admin to control which cluster-scoped resources will automatically be migrated in non-admin migration.

**Comment by sseago** [comment]
ResourceQuotas are created in the namespace for which they apply. So the whitelist wouldn't be needed for them. As for the general whitelist, how will that interact with velero in the case where velero itself (or the plugins) pulls resources in? PVs connected to PVCs are pulled in by velero explicitly. Same with CRDs. For others, such as SCCs, the plugin pulls those in as required to prevent migration failure.

**Comment by dymurray** [comment]
Following up from some thoughts I've had after discussing this with Scott in slack... the more I've thought about this, I think that instead of passing this list of included resources in as annotations to the plugins, we should consider this to be an `alwaysInclude` list. In fact, it makes me wonder if we should add a new `include` field into the migplan spec. This would allow us to enable the ability to add label selector usage and other items in the API.

**Comment by dymurray** [comment]
@sseago the more I dig into this, I'm realizing it probably just makes more sense while I'm doing this to expose the full capabilities of the includes/excludes list in Velero. What do you think about a new field on the `MigPlanSpec`:

```
type IncludesExcludes struct {
  IncludeNamespaces []string
  IncludeResources []string
  ExcludeNamespaces []string
  ExcludeResources []string
  IncludeClusterScoped bool
  LabelSelector map[string]string
}
```

That just exposes these fields to be passed into the Velero backup? And then for now the UX doesn't have to change, we can still use `IncludeNamespaces` but also leave the door open to more customized migrations down the road.

**Comment by dymurray** [comment]
After discussing this further with Jeff, I think it's a bad idea to expose these APIs on the migplan at this moment and will make the validations for non-admin even more difficult than they already are. If we exposed `LabelSelector` then we would need to validate everything with the label selector can be read by the non-admin user. Not impossible, but no need to add the extra complexity right now.

In fact, the best way to solve this is to simply expose a whitelist for the admin on the `MigrationController` CR and have the tenant controllers respect this whitelist.

This means *NO* changes to the `MigPlan` spec today.

**Comment by dymurray** [comment]
After discussing with Scott... the best way to achieve the same requirement is to make this a blacklist instead of a whitelist. This allows us to document up front which list of cluster-scoped resources will be automatically pulled in for a non-admin migration:

* PersistentVolumes
* ClusterResourceQuotas
* ClusterRoles
* ClusterRoleBindings
* SecurityContextConstraints

Then, if a non-admin wishes to disable some of these resources to be automatically included (if a ns-scoped resource references it) they can simply list in the blacklist what they wish to exclude.

We will then just pass this in as `excludedResources`

**Comment by sseago** [comment]
@dymurray except we need to exclude PersistentVolumes from that list (those aren't optional). What about CRD? Do we include CRD in the list?

**Comment by dymurray** [comment]
@sseago I updated to include CRDs. I don't think we should exclude PVs from that list. It might be desired an admin doesn't want a non-admin to migrate any storage and 9/10 times a non-admin user won't have access to PVs on a cluster.

Obviously we will want to document that if you exclude PVs and someone migrates a PVC backed app then all the data will be lost in a `copy` scenario and in a `move` scenario nothing would happen.

I know this seems counter-intuitive as we are giving an admin the ability to really screw up things, but if a user doesn't have access to PVs it might be desired from an admin standpoint to not automatically give them the ability to mutate those resources.

**Comment by sseago** [comment]
I wonder if when we add PersistentVolumes to excludeResources if we should also exclude PersistentVolumeClaims at the same time. Skipping both would fail more cleanly than just skipping PVs. This should probably also short-circuit PV discovery and the hasPVs checks in the controller so we won't even bother trying to create stage pods, etc.

**Comment by sseago** [comment]
Also, note that PVs and PVCs wouldn't go onto the same place. Those would show up by *removing* PVs and PVCs from the `includeResources` block on the *stage* backup, while all of the others on the list would show up by *adding* them to the `excludeResources` block on the *initial* backup.
