### ISSUE TITLE
Add `MigToken` CRD for non-admin UX improvement

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#512]
We need a new CRD `MigIdentity` which will contain a user's identity token to be consumed by a MigPlan. Today we are simply using a secretRef, but we want the controller to reconcile on the `MigIdentity` objects to validate whether they can currently authorize against the given cluster. This will be used to determine if a user's oauth token has expired.

**Comment by dymurray** [comment]
The `MigIdentity` CRs will be created in the tenant's namespace. it should contain at least the following spec fields:

```
type MigIdentitySpec struct {
  identitySecretRef kapi.SecretReference
  migclusterRef kapi.ObjectReference
  type: string // The type of identity token this is (oauth/serviceaccount)
  expired: boolean // Only used with oauth, but could also indicate an SA token has been deleted
}
```

There will be a 1-1 mapping of MigIdentity to MigCluster. The controller will be responsible for reconciling on the migIdentitys at a predetermined length of time (5-10 mins?) or on the change of the identity secret. If an oauth token has expired, set the spec field accordingly.

Prior to running a migration, all migIdentities should be validated once more to ensure the token hasn't expired and is valid.

**Comment by alaypatel07** [comment]
@dymurray closing this issue since it is checked in #388. Please re-open if required. Thanks
