### ISSUE TITLE
Bad hooks not failing the plan properly. The plan also won't work again until cleanup is done.

### ISSUE THREAD

**Issue by jmontleon** [konveyor/mig-controller#519]

**Comment by jmontleon** [comment]
https://github.com/konveyor/mig-controller/pull/518
https://bugzilla.redhat.com/show_bug.cgi?id=1829390

An alternate failure scenario was discovered and is handled here in the PR. Added an owner label to correlate jobs/configmaps to a specific migmigration so that failed jobs won't prevent a rerun from working correctly.

**Comment by djwhatle** [comment]
Closed by https://github.com/konveyor/mig-controller/pull/518
