### ISSUE TITLE
Handle ResourceQuotas for stage pods

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#537]
**Description**
When ResourceQuotas are set on the destination cluster namespaces, we must set request and limit values for CPU and memory otherwise Stage Pods will fail to schedule.

**Links**
Implemented by: https://github.com/konveyor/mig-controller/pull/536
Jira: [MIG-202](https://issues.redhat.com/browse/MIG-202)

**Comment by djwhatle** [comment]
@sseago the Jira doesn't have a lot of detail on this issue. Can you provide some context?

**Comment by sseago** [comment]
Basically if there's a ResourceQuota in a namespace being migrated (or a ClusterResourceQuota which matches the namespace being migrated) that specifies a quota limit for CPU or memory, then any pod that doesn't specify request and limit values for CPU and memory will fail to schedule, which means that the stage pods as we were creating them would fail to schedule. The starting point for this PR is to specify limit/request values of 100m for CPU and 128Mi for memory for all stage pods. However, that initial fix causes a different sort of failure if there are LimitRanges defined with minimum CPU or memory per-pod or per-container which are higher than these defaults, so I also needed to find the largest minimum CPU and memory values from the LimitRanges for each namespace and use the larger of this and the default value in creating stage pods.
