### ISSUE TITLE
Check the GVK's available for running SAR checks on non-admin 

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/mig-controller#550]
The non-admin branch has a list of resource to run the SAR 
checks [1]. The list is missing `extensions` groups APIs like
for Deployments and ReplicaSets. In order to add those, the
controller needs to dynamically check what API's are available
on each cluster and run the SAR check on that `group-kind`.

We can explore re-using the logic in GVK differ to dynamically 
give us a list of all GV required during migration and then run
SAR check against that

1. https://github.com/konveyor/mig-controller/pull/548/files#diff-b7611884082a3e4806fc90fd2bc998f3R114

**Comment by djwhatle** [comment]
Related to non-admin #388
