### ISSUE TITLE
NFS server accessibility validation running when not needed (NFS copy)

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#558]
## **Problem Description:**
Migrating from NFS (src) to gp2 (target) using **NFS copy,** it isn't necessary for us to run a validation on NFS accessibility from the target cluster, but a warning condition is still being raised.

Reported by Sergio Regidor.

**PVC Migration Selections**
```
pvc:
      accessModes:
      - ReadWriteOnce
      name: nginx-html
      namespace: nginx-pv
    selection:
      action: copy
      copyMethod: filesystem
      storageClass: gp2
    storageClass: nfs
    supported:
      actions:
      - copy
      copyMethods:
      - filesystem
      - snapshot
```

**Warning Condition**
```
  - category: Warn
    lastTransitionTime: "2020-06-04T17:14:13Z"
    message: NFS servers [172.30.184.84] not accessible on the destination cluster.
    status: "True"
    type: NfsNotAccessible
```

---

**Full MigPlan**
```
kind: MigPlan
metadata:
  annotations:
    openshift.io/touch: 9b65071a-a688-11ea-a1b5-0a580a81020c
  creationTimestamp: "2020-06-04T17:14:04Z"
  generation: 3
  labels:
    controller-tools.k8s.io: "1.0"
  name: nginx-pv-migplan-1591290259
  namespace: openshift-migration
  resourceVersion: "71654"
  selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/openshift-migration/migplans/nginx-pv-migplan-1591290259
  uid: f72c2199-6d25-4f29-8512-136e58199ad4
spec:
  destMigClusterRef:
    name: host
    namespace: openshift-migration
  migStorageRef:
    name: automatic
    namespace: openshift-migration
  namespaces:
  - nginx-pv
  persistentVolumes:
  - capacity: 1Mi
    name: pvc-bd52bd24-a686-11ea-a19e-0e9d0082032d
    pvc:
      accessModes:
      - ReadWriteOnce
      name: nginx-logs
      namespace: nginx-pv
    selection:
      action: copy
      copyMethod: filesystem
      storageClass: gp2
    storageClass: nfs
    supported:
      actions:
      - copy
      copyMethods:
      - filesystem
      - snapshot
  - capacity: 50Mi
    name: pvc-bd5c1f75-a686-11ea-a19e-0e9d0082032d
    pvc:
      accessModes:
      - ReadWriteOnce
      name: nginx-html
      namespace: nginx-pv
    selection:
      action: copy
      copyMethod: filesystem
      storageClass: gp2
    storageClass: nfs
    supported:
      actions:
      - copy
      copyMethods:
      - filesystem
      - snapshot
  srcMigClusterRef:
    name: source-cluster
    namespace: openshift-migration
status:
  conditions:
  - category: Required
    lastTransitionTime: "2020-06-04T17:14:10Z"
    message: The `persistentVolumes` list has been updated with discovered PVs.
    reason: Done
    status: "True"
    type: PvsDiscovered
  - category: Warn
    lastTransitionTime: "2020-06-04T17:14:13Z"
    message: NFS servers [172.30.184.84] not accessible on the destination cluster.
    status: "True"
    type: NfsNotAccessible
  - category: Required
    lastTransitionTime: "2020-06-04T17:14:14Z"
    message: The storage resources have been created.
    status: "True"
    type: StorageEnsured
  - category: Required
    lastTransitionTime: "2020-06-04T17:14:15Z"
    message: The migration registry resources have been created.
    status: "True"
    type: RegistriesEnsured
  - category: Required
    lastTransitionTime: "2020-06-04T17:14:15Z"
    message: The migration plan is ready.
    status: "True"
    type: Ready
  - category: Advisory
    lastTransitionTime: "2020-06-04T17:14:27Z"
    message: Limited validation; PV discovery and resource reconciliation suspended.
    status: "True"
    type: Suspended
  observedDigest: f948e91253f8276c5e2a2e27f7ed0401eb543dea8425f931b574f9bb8e84ed22
```

**Comment by djwhatle** [comment]
Marek, this would be a great first issue to build a fix for. 

**The problem is:**
- We want to verify that NFS server is accessible when PVC **move** (`action: move`) has been selected for an NFS PV.
- In this case, PVC **copy** (`action: copy`) has been selected, but the validation is incorrectly raising a warning condition.
   ```
  - category: Warn
    lastTransitionTime: "2020-06-04T17:14:13Z"
    message: NFS servers [172.30.184.84] not accessible on the destination cluster.
    status: "True"
    type: NfsNotAccessible
   ```

---

Somewhere in our MigPlan validation code we are incorrectly running this NFS accessibility validation for `action: copy` PVs. This isn't necessary because:
-  When `action: copy` is selected, PVC contents will be first copied up to S3, then copied down from S3 into a new PVC. Direct network connection is not required here. 
- When `action: move` is selected, we will directly attach NFS share contents to the destination cluster.

---

**Resources**

- Read about mig-controller [validations](https://github.com/konveyor/mig-controller/blob/bb0ccadd8c76127df1f539822aaf595b474ab76c/docs/devguide.md#validation)
- Look at [migplan/validation.go ](https://github.com/konveyor/mig-controller/blob/bb0ccadd8c76127df1f539822aaf595b474ab76c/pkg/controller/migplan/validation.go)
- Refer to the MigPlan YAML above to reproduce the issue. You'll need a source cluster namespace with NFS PVCs to reproduce this. mig-agnosticd OCP 3.x clusters have this set up by default.

**Comment by aufi** [comment]
Hi @djwhatle, thanks for description in previous comment - it looks good and logical, however I tried simulate the same situation with rocket-chat demo app and there is a small difference in the MigPlan - missing ```storageClass: nfs``` before ```support:``` section.

```
  persistentVolumes:
  - capacity: 10Gi
    name: vol139
    pvc:
      accessModes:
      - ReadWriteOnce
      name: rocketchat-data-claim
      namespace: rocket-chat
    selection:
      action: copy
      copyMethod: filesystem
      storageClass: gp2
    supported:
      actions:
      - copy
      - move
      copyMethods:
      - filesystem
      - snapshot
``` 

Should I focus on finding out if the ```storageClass``` key placed on the same level as ```pvc``` is correct or on the validation function modification?

**Comment by aufi** [comment]
Hi @djwhatle, thanks for description in previous comment - it looks good and logical. I tried simulate the same situation with rocket-chat demo app and couldn't reproduce it (migration passed without warnings). There was a small difference in the MigPlan - missing ```storageClass: nfs``` before ```supported:``` section. So I added it into to migplan yaml and created a new migplan with oc command. However when started the migration from UI, the storageClass: nfs disappeared again and migration passed.

Would it be possible provide more details on reproducing this issue/recommendhow setup the storageClass key to nfs? Thanks!

```
  persistentVolumes:
  - capacity: 10Gi
    name: vol139
    pvc:
      accessModes:
      - ReadWriteOnce
      name: rocketchat-data-claim
      namespace: rocket-chat
    selection:
      action: copy
      copyMethod: filesystem
      storageClass: gp2
# storageClass removed
    supported:
      actions:
      - copy
      - move
      copyMethods:
      - filesystem
      - snapshot
```

**Comment by djwhatle** [comment]
Hey @aufi. The list of supported actions and copyMethods for PVC migration is set automatically by mig-controller and cannot be hand-modified (any changes made by hand will be overwritten). As a user, you're only allowed to modify the `selection` key.

I would recommend reaching out to Sergio Regidor, the original reporter of this issue, for more info on reproducing the problem.

**Comment by djwhatle** [comment]
@aufi what were the actual reproducer steps for this issue? It sounds like the information here was not enough and that Sergio provided some additional info.

**Comment by aufi** [comment]
Reproducer information from Sergio mentioned on this issue was good,  but it was necessary setup NFS storageClass on OCP3 source cluster and update migrated application to use it.

Sergio provided ansible playbook to setup NFS on OCP3, however I had issues with its execution, so he did the NFS setup on my OCP3 installation for me.

The application I used was https://github.com/konveyor/mig-demo-apps/tree/master/apps/rocket-chat with modified PVC:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-data-claim
  namespace: rocket-chat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
```

**Comment by jwmatthews** [comment]
@aufi just a note that creating a 'nfs' storageClass is not typical.   For NFS PVs it is common to precreate the PVs manually without referencing a specific storageclass.  

Storageclass is used more for dynamic provisioning of PVs like EBS which created by a dynamic-provisioner or for grouping PVs together for some kind of characteristic. 

There is nothing wrong with creating a new storageclass and grouping NFS PVs with it, just wanted you to know it's not a requirement.
