### ISSUE TITLE
Check for nil pointers returned from `client.List` queries in model.go

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#568]
Example: https://github.com/konveyor/mig-controller/blob/master/pkg/apis/migration/v1alpha1/model.go#L30-L40

The lack of checking for nil pointers here has lead to several defects, we should refactor model.go to handle this more gracefully, or else consider removing the helper functions that sometimes return these nil pointers.

@jortel, I believe your idea was that we should remove the `List***()` functions from model.go that don't perform any dereferencing assistance. 

I think another idea would be to explicitly construct and return an error when a nil ptr is detected on the returned `list.Items`.

**Comment by aufi** [comment]
This issue looks good to start with (discussed with @mansam), going to work on this.

**Comment by aufi** [comment]
@djwhatle Hi Derek, is there a way how to reproduce this issue?

**Comment by djwhatle** [comment]
Hey @aufi , after discussing this with Jeff I realized there are a lot of subtle side effects that may make this fix tricky.

I'll reach out to you out of band with some recommended alternatives. Pulling the low-hanging-fruit label from this issue.

**Comment by aufi** [comment]
Thanks for info, I'm going to look on other issue.

**Comment by djwhatle** [comment]
This issue is too vague, closing.
