### ISSUE TITLE
Add ability to start/stop migration at specific phases

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#569]
With some customers we have found that it would be beneficial to start a failed migration at a specific phase rather than starting from scratch everytime. I understand this comes with it's own set of issues as it's tough to know what exactly has been created/cleaned up in the past migration attempts but we should consider allowing the user to have more granular control over the backup/restore process by specifying which phase they'd like to pause/stop the migration at and which phase they would like to start the migration at.

**Comment by djwhatle** [comment]
This is part of #704
