### ISSUE TITLE
MigMigration fails when migrating templateinstance resource

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#581]
This has been seen in a couple environments now. Migration templateinstances causes the velero restore to fail making the migration itself fail.

For a workaround we excluded templateinstance resources from the migration controller in a custom image. We need to fix this in the controller itself by exposing the ability to exclude certain resources, or we need to write a proper templateinstance plugin to skip it or handle the resource properly.

Error on migmigration:
```
  errors:
    - >-
      TemplateInstance.template.openshift.io
      "e8a3b6a4-ba40-11ea-bbb8-0a580a800006" is invalid:
      spec.requester.username: Forbidden: you do not have permission to set
      username
  itenerary: Failed
```

**Comment by jwmatthews** [comment]
Closed by https://github.com/konveyor/mig-controller/pull/588
