### ISSUE TITLE
add appropriate printer columns for mig* resources

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/mig-controller#599]
I recently ran into a scenario where I opened two migplans
and started migrations from UI. As expected, the UI created
two migmigration resources, one of them failed, I can see it 
from UI. When I go the cli and run `oc get migmigration`, it
is not helpful since it is not immediately clear to me which 
migmigration is associated with which migplan. Adding a
kubectl printer column would help make it obvious for user
make this association. More info here[1]

1. Additional printer columns heading [here](https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html)

**Comment by djwhatle** [comment]
**Considerations for this issue:**

- [ ] Need to achieve consensus with team on which fields should be exposed for each Mig* CR
- [ ] Need to ensure the version of kubebuilder we're using supports `printcolumn` 
```
// +kubebuilder:printcolumn:name="Spec",type="integer",JSONPath=".spec.cronSpec",description="status of the kind"
// +kubebuilder:printcolumn:name="Replicas",type="integer",JSONPath=".spec.Replicas",description="The number of jobs launched by the CronJob"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
```

**Comment by djwhatle** [comment]
I propose this set of printer columns for Mig* resources:

@alaypatel07 @eriknelson please review and comment with suggested revisions.

**MigAnalytic**
- `MigPlan` - (string) spec.MigPlanRef.Name
- `PercentComplete` - (num%) analytic.Status.Analytics.PercentComplete
- `ImageCount` - (num) analytic.Status.Analytics.ImageCount
- `PVCount` -  (num) analytic.Status.Analytics.PVCount

**MigCluster**
- `Ready` - (true/false) migcluster.Status.Conditions[Type=Ready].isPresent
- `IsHostCluster` - (true/false) migcluster.Spec.Host
- `ClusterURL` - (string) migcluster.Spec.clusterURL

**MigHook**
- `Ready` - (true/false) mighook.Status.Conditions[Type=Ready]

**MigMigration**
- `MigPlan` - (string) migmigration.Spec.MigPlanRef
- `Phase` - (string) migmigration.Status.Phase
- `Ready` - (true/false) migmigration.Status.Conditions[Type=Ready].isPresent
- `IsStage` - (true/false) migmigration.Spec.Stage

**MigPlan**
- `SrcCluster` - (string) migplan.Spec.SrcMigClusterRef.name
- `DestCluster` - (string) migplan.Spec.DestMigClusterRef.name
- `MigStorage` - (string) migplan.Spec.MigStorageRef.name
- `Ready` - (true/false) migplan.Status.Conditions[Type=Ready].isPresent

**MigStorage**
- `Ready` - (true/false) migstorage.Status.Conditions[Type=Ready].isPresent
