### ISSUE TITLE
Consider improving 'make run' experience to avoid dev pitfalls

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#613]
Some issues a contributor might run into hacking on the controller with `make run`

- Lack of environment variables that would have been set by mig-operator on mig-controller pod lead to differing behavior from mig-operator based deploy. (e.g. default ExcludedResources list set via env var)

- Web UI will fail in confusing ways due to lack of connection from Web UI to Discovery Service (local running controller discovery service won't be available via OpenShift routing system)

---

I suggest we consider removing `make run` and advising everyone to deploy through operator for behavioral consistency. I'd also be open to improving some of the above aspects if folks find `make run` valuable.

**Comment by djwhatle** [comment]
The downside of removing `make run`: it takes ~4 minutes for a `build + push + update migrationcontroller + reconcile + restart pod` cycle on my machine. This is not a very fast iteration time for quick changes.

**Comment by djwhatle** [comment]
Another point to add: all vars set by mig-operator for mig-controller should arguably be set into the mig-controller ConfigMap and not directly on the Pod, this way `make run` will continue to function as expected. We should do a round of changes to ensure that mig-operator is _not_ settings vars directly on the mig-controller pod.

**Comment by sseago** [comment]
There are times where the 4 minute per-change hit would be a significant productivity hit. I'm thinking in particular when iterating over a series of small changes, making sure each small change has the desired effect, although not creating separate commits or updating the PR for each change.

Regarding explicit env vars vs. using a ConfigMap, the downside of using a ConfigMap is that if you update a variable in the ConfigMap, the deployment won't necessarily kick off a new pod since the Deployment yaml doesn't change, while with explicit env vars the pod will always restart on change. We had a problem with this at one point, where we then moved a ConfigMap into separate env vars in Spec. I'm not sure whether this has changed since then or not, though.

**Comment by mansam** [comment]
Removing `make run` also makes it more difficult to debug, since I can't attach a debugger to the controller running in a pod.

**Comment by djwhatle** [comment]
> Regarding explicit env vars vs. using a ConfigMap, the downside of using a ConfigMap is that if you update a variable in the ConfigMap, the deployment won't necessarily kick off a new pod since the Deployment yaml doesn't change, while with explicit env vars the pod will always restart on change. We had a problem with this at one point, where we then moved a ConfigMap into separate env vars in Spec. I'm not sure whether this has changed since then or not, though.

We could overcome this by manually deleting the mig-controller Pod (or doing a rollout) if mig-operator performs a settings change to the configmap. This would be a really easy fix (check result of ansible task that sets configmap) and would allow for moving all env vars to configmap where they could be consumed by `make run` 

> Removing `make run` also makes it more difficult to debug, since I can't attach a debugger to the controller running in a pod.

I agree. I don't usually use a debugger but I know several folks on the team do and this would cause problems for that.

**Comment by djwhatle** [comment]
@mansam @sseago Proposed fix that will bring `make run` back in line with mig-operator behavior: https://github.com/konveyor/mig-controller/issues/616 , please review if you have thoughts.

**Comment by djwhatle** [comment]
Just to add one more argument in favor of keeping `make run` closer to the "operated" controller experience: It would be a whole lot harder to run tracing for performance tracking if I can't run the controller locally.

**Comment by djwhatle** [comment]
Closing, will use #616 as solution
