### ISSUE TITLE
Handle ImageStreamTag restore failures related to resource dependencies and race conditions

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#621]
Copied from **Jira:** [MIG-186](https://issues.redhat.com/browse/MIG-186)

---

**Summary**

There are several situations that can happen right now involving ImageStreamTag restore that can result in failures on restore. The failure may be different depending on whether the underlying image is internal or external, whether the tag is an alias tag or not, and whether the tag points to a resource that still exists or one which has been deleted. To handle all of these cases, the following tasks are required:

---

**Fix needed in mig-controller:**

When migrating internal images, the actual ImageStreamTag isn't created until the docker image copy has completed. The fix for this is to move internal image copy to the stage backup/restore. In addition to resolving part of the race condition here, this will also allow us to take advantage of incremental migration for image content in addition to PV content. - #620 

This BZ reports one aspect of this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1816148

**Comment by djwhatle** [comment]
#620 handles work item 1 from above.

**Comment by sseago** [comment]
I think item #1 is probably the only one that's a mig-controller fix. #3 is in velero, and #2,4,5 are in our velero plugins.

**Comment by djwhatle** [comment]
@sseago thanks, just realized this. Removing the others.
