### ISSUE TITLE
question: how does migplan validation work

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/mig-controller#624]
It looks like we use a Field Indexer on migplan [here](https://github.com/konveyor/mig-controller/blob/55a8458015330468a6b9a12047f3ff3452ffdac8/pkg/controller/migplan/migplan_controller.go#L117)

I have couple of questions regarding the implementation:

1. Shouldn't the field [here](https://github.com/konveyor/mig-controller/blob/55a8458015330468a6b9a12047f3ff3452ffdac8/pkg/apis/migration/v1alpha1/migplan_types.go#L48) be `spec.closed`. From the [documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/)
 it looks like we need the spec part, but if someone has observed
 this run without, I am curious to learn

2. The issue [here](https://github.com/kubernetes/kubernetes/issues/53459) suggests that for our CRD, 
 field selector will not work on any fields except metadata.name 
and metadata.namespace. Again if anyone has observed this run, 
curious to learn

With the above, I am perplexed as to if the `ListPlans` [function](https://github.com/konveyor/mig-controller/blob/55a8458015330468a6b9a12047f3ff3452ffdac8/pkg/controller/migplan/validation.go#L566) 
ever returns a non-empty list.

**Comment by djwhatle** [comment]
Closing due to staleness, please re-open if still looking for an answer. Probably best to reach out to Jeff directly since he added this.
