### ISSUE TITLE
Check for matching MTC version at beginning of MigCluster reconcile

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#633]
- Help user avoid inadvertently running a migration with mismatched versions of MTC on source/target cluster
- Help user realize they need to upgrade MTC on both src/target cluster, not just on target

If user runs with mismatched MTC versions, they could experience undefined behavior. We should raise a condition on the MigCluster if this is detected.

Suggested by @sseago 

Related:  https://issues.redhat.com/browse/MIG-309

**Comment by sseago** [comment]
Actually we should probably raise it on the migcluster instead. That way we'll catch it immediately if the user adds a new cluster that's mismatched. Assuming this condition makes the cluster non-ready (which I think it should), this will also prevent migplans and migmigrations from running.

**Comment by djwhatle** [comment]
I don't know that we currently include a `VERSION` string anywhere in our shipped code that is currently accessible from mig-controller. Part of solving this issue will be figuring out how to reliably access `VERSION` from mig-controller.

We'll also need to make sure this doesn't block migrations if either end of the system (src/target) is running `latest` or `make run`.

**Comment by sseago** [comment]
The absence of an obvious way to check version is part of why for the 1.2.5 PR I had suggested limiting validation to the presence of that ConfigMap. Maybe the answer is *adding* a version string to that very ConfigMap. That feels like a reasonable place to put it. As for the "make run" scenario, anyone running latest or manually via "make run" will also need that ConfigMap to exist. If latest leaves that value blank, then if all migclusters use the same blank value, they'll match. Same if it's something like "devel". In my "make run" environment, I actually run with an installed mig-operator which just doesn't run the controller or UI, so I'd have the configmap present there.

**Comment by sseago** [comment]
We may need the same version string set as an environment variable on the controller (perhaps pulled from the ConfigMap for the host cluster), that way the migcluster validation only needs one cluster context for ConfigMap lookup -- it compares that value to the env var.

**Comment by djwhatle** [comment]
@ibolton336 is looking at this issue right now. 

I think from the conversation above, our approach should look something like this:

1. Modify mig-operator to add an `OPERATOR_VERSION` field to the `migration-cluster-config` configmap. This should provide either the correct version, or "latest" if running an unreleased build [(link)](https://github.com/konveyor/mig-operator/blob/a1dbdb34d677ba95dae500db87a8bf46466ef396/roles/migrationcontroller/templates/mig-cluster-config.yml.j2)

2. As part of MigCluster reconcile, pull the `migration-cluster-config` configmap and grab the `OPERATOR_VERSION` field. Drop it into a new `MigCluster.Status.OperatorVersion` field.

3. As part of MigPlan validation, check if both involved MigClusters have same OperatorVersion. If not, raise a warning condition notifying the user of the version difference. 
 
4. On the MigClusters page in the UI, pull the version off the `MigCluster.Status.OperatorVersion` field.
![image](https://user-images.githubusercontent.com/7576968/106188138-9511bb80-6174-11eb-9d69-28def3161be3.png)
