### ISSUE TITLE
fix problems with migregistry deployment

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/mig-controller#635]
For transferring images, we deploy mig-registry on both source
and destination clusters. While tinkering with the code, found some
issue, using this as a tracker to note down stuff as I learn:

- [x] registry is deployed as deploymentconfig with imagestream
       it can be simplified with a deployment and a static image
       - addressed in #632 
- [x] some functions have wierd flow for example 
       `ensureRegistryImageStream`. Need to make the flow more 
       readble to maintain sanity - concluded that the workflow is
       required
- [x] Evaluate the need for Equals* methods for migregistry
       deployments related objects. Ideally we should be able to hash
       the spec and compare the has instead of complex comparison
       logic - look at Scott's comments
- [ ] add health checks to mig-registry: Issue #626 
- [ ] revise the workflow for getting mig-registry related resources

    The current workflow is as follows

       1. construct the resource (deployment, service) using secret name
       2. get the list of resources with migplan label selector
       3. return the first resource in the list as the found resource
       4. compare the found resource with constructed resource in step 1
       5. if comparision is not equal attempt to create the resource constructed
                in step 1.
       6. else return

     The workflow should be:

       1. construct the resource
       2. Get the resource with the name from step 1
       3. if found compare, else create
       4. if compare and unqual update else return

**Comment by sseago** [comment]
The reason for the Equals methods which only compare some fields is that the controller logic *updates* the resource if any of those fields differ from expectations. We don't want a strict hash, because we don't want to update unless certain fields are changed or we'll end up constantly updating when we don't need to, risking conflicts which force requeuing. Perhaps a better name than Equals* -- NeedsUpdate* or some such to be clear?

**Comment by djwhatle** [comment]
Resolved by #681
