### ISSUE TITLE
Namespaces [cam-test] not found on the source cluster in CAM CLI 

### ISSUE THREAD

**Issue by ashoks27** [konveyor/mig-controller#640]
Hello All ,

I have read in some comments saying the " Namespace not found on source Cluster " issue has been fixed in some thread, But I still I am getting this error while creating the Migplan in my CAM CLI in openshift version 4.4 . Could you please let to know how it can be fixed. Thanks.

[ashok@oc4377604745 ~]$ oc -n openshift-migration describe migplan  migplan-cam
Name:         migplan-cam
Namespace:    openshift-migration
Labels:       controller-tools.k8s.io=1.0
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"migration.openshift.io/v1alpha1","kind":"MigPlan","metadata":{"annotations":{},"labels":{"controller-tools.k8s.io":"1.0"},"...
              openshift.io/touch: 556a7446-e5dc-11ea-9d5f-fe1c332bb863
API Version:  migration.openshift.io/v1alpha1
Kind:         MigPlan
Metadata:
  Creation Timestamp:  2020-08-24T07:32:06Z
  Generation:          4
  Resource Version:    9074360
  Self Link:           /apis/migration.openshift.io/v1alpha1/namespaces/openshift-migration/migplans/migplan-cam
  UID:                 5d07d04c-8419-46a8-b46a-0a00b7d6496d
Spec:
  Dest Mig Cluster Ref:
    Name:       migcluster-local
    Namespace:  openshift-migration
  Mig Storage Ref:
    Name:       migstorage-sample
    Namespace:  openshift-migration
  Namespaces:
    ashok
  Src Mig Cluster Ref:
    Name:       migcluster-remote
    Namespace:  openshift-migration
Status:
  Conditions:
    Category:              Critical
    Last Transition Time:  2020-08-24T07:34:58Z
    Message:               Namespaces [ashok] not found on the source cluster.
    Reason:                NotFound
    Status:                True
    Type:                  NamespaceNotFoundOnSourceCluster
  Excluded Resources:
    imagetags
    templateinstances
    clusterserviceversions
    packagemanifests
    subscriptions
    servicebrokers
    servicebindings
    serviceclasses
    serviceinstances
    serviceplans
  Observed Digest:  936655c52f90b395d40d6a54da10cee5beae2bbdf15f6754496fa1ae50d2b02f
Events:             <none>
[ashok@oc4377604745 ~]$

**Comment by ashoks27** [comment]
Could someone please update on this issue.. The namespace is available on the source cluster , but still it does show the error.

Thanks.

**Comment by jwmatthews** [comment]
@ashoks27 I would check if the Service Account you configured for the Source MigCluster has access to 'ashok' namespace on your source.

We recommend using the service account token our operator creates on the source so it has sufficient privileges.

If that is OK, the next thing to debug would be to look at the controller logs and see if we can find more info of why the controller is not able to access the namespace on source cluster.

What version of CAM are you seeing this with?

**Comment by ashoks27** [comment]
@jwmatthews Thanks for your response.. CAM version we are using is 1.2.5. This issue I have raised last month and it has been fixed after we included the the option Is secure as True in Migcluster configuration.  I have raised one more issues recently on the same #682 . Would you please help to provide solution for it. Thanks.
