### ISSUE TITLE
[MIG-323] Enhance traceability by improving logging and emitting events

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#661]
## Issue
We want to make our logs more useful for identifying root cause of issues reported by users. 

## Current state of logging
We minimally log by design, just showing current migration phase + any critical errors and their associated stack trace

## Suggested Solution
@alaypatel07 had the idea of writing a log message any time we use our k8s client to take an action on the world outside of our controller. I think this would greatly increase transparency into what mig-controller is doing, and this mirrors the pattern I've seen in things like ansible-operator.

**Goals**
 - Increase the likelihood that we'll be able to diagnose a user issue with just the info provided from must-gather
 - Show what controller is working on in large migrations where a single Migration phase may take a long time and run many sub-actions
 - Cover the case where no stack trace is logged but controller still isn't doing the right thing / is stuck
 - Log all of our Create/Delete/Update interactions with k8s objects
 - Consider adding an "Exit message" summarizing why a phase isn't yet progressed to next step.

---

_Footnote: OpenShift log levels_
```
0 – Errors and warnings only
2 – Normal information
4 – Debugging information
6 – API- debugging information (request / response)
8 – Body API debugging information
```

**Comment by alaypatel07** [comment]
I am working on an enhancement for this, will update soon, thanks!

**Comment by djwhatle** [comment]
@eriknelson 

Enhancement doc: https://github.com/konveyor/enhancements/pull/6
First logging PR: https://github.com/konveyor/mig-controller/pull/698

I think Alay may be planning to do more logging PRs but not sure.

**Comment by shubham-pampattiwar** [comment]
@eriknelson @djwhatle PR for Migstorage controller is merged. I will be raising more PRs for other controllers.

**Comment by alaypatel07** [comment]
IMO we should keep this open at least until, MigCluster, MigPlan, and MigMigration are covered with new logging pattern

**Comment by alaypatel07** [comment]
Completed via 

#736 #746 #731 #745

**Comment by alaypatel07** [comment]
Actually this is pending a mig-operator PR for RBAC changes

**Comment by alaypatel07** [comment]
done via  https://github.com/konveyor/mig-operator/pull/491
