### ISSUE TITLE
Allow user to control Rollback of a migration at will or on failure

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#663]
**Jira**: https://issues.redhat.com/browse/MIG-249

As a User of MTC, I want the ability to rollback a migration, either because a partial failure has been detected or because I want to consider this migration a 'test'.

_As part of a rollback:_

 - Remove the migrated pieces on the destination cluster
 - Unmount shared remote volumes on destination
 - Scale the applications running source cluster back to their original replica counts
 - Remount shared remote volumes

**Comment by djwhatle** [comment]
**Relevant mig-controller files:**
 - [task.go](https://github.com/konveyor/mig-controller/blob/master/pkg/controller/migmigration/task.go) - the core of the migration state machine. 
 - 

**Relevant past PRs:**
 - [Bug 1844638: Add settings switch controlling whether FailedItinerary (auto-rollback) gets used](https://github.com/konveyor/mig-controller/pull/560)

**Original Implementation PRs related to "cancel" and "rollback"**
 - [Added cancelling feature](https://github.com/konveyor/mig-controller/pull/452)
 - [App backscaling on demand](https://github.com/konveyor/mig-controller/pull/458)
 - [Allow deletion of backup and restore after migration is cancelled](https://github.com/konveyor/mig-controller/pull/465)
 - [Ignore cancelled final migration in validation step](https://github.com/konveyor/mig-controller/pull/476)

**Comment by djwhatle** [comment]
Hey @aufi! I was talking with @jortel earlier today about this issue to nail down the required changes .  Here's a summary of requirements we are proposing:

---

-  Add a new `Rollback` itinerary
-  Remove the global "rollback on failure" switch that I implemented in response to BZ 1844638 (see above comment). Instead, add a new `spec.rollback` field to the MigMigration CR
-  Remove (almost) rollback specific steps from `CancelItinerary` and `FailedItinerary`. These steps will be moved to the new `RollbackItinerary`. 

```
var CancelItinerary = Itinerary{
	Name: "Cancel",
	Steps: []Step{
		{phase: Canceling},
		{phase: DeleteBackups},
		{phase: DeleteRestores},
		{phase: EnsureStagePodsDeleted, all: HasStagePods},
		{phase: EnsureAnnotationsDeleted, any: HasPVs | HasISs},
		{phase: Canceled},
		{phase: Completed},
	},
}

var FailedItinerary = Itinerary{
	Name: "Failed",
	Steps: []Step{
		{phase: MigrationFailed},
		{phase: EnsureStagePodsDeleted, all: HasStagePods},
		{phase: EnsureAnnotationsDeleted, any: HasPVs | HasISs},
		{phase: Completed},
	},
}

var RollbackItinerary = Itinerary{
	Name: "Rollback",
	Steps: []Step{
		{phase: Rollback},
		{phase: DeleteBackups},
		{phase: DeleteRestores},
		{phase: EnsureStagePodsDeleted, all: HasStagePods},
		{phase: EnsureAnnotationsDeleted, any: HasPVs | HasISs},
		{phase: DeleteMigrated},
		{phase: EnsureMigratedDeleted},
              # note this one may be tricky since quiesce is currently
              #  on the MigMigration. Ping @jortel for ideas on this.
		{phase: UnQuiesceApplications, all: Quiesce}, 
		{phase: RollbackComplete},
		{phase: Completed},
	},
}

```

- Change rollback from acting on a particular MigMigration to acting on the entire plan. (@jwmatthews can you ACK this? We think rollback of a single migration is potentially confusing since it could end up deleting the dest namespaces). This change will require that we label resources with the MigPlan that migrated them, and remove those labels later. I'm not sure if we do this already or if we only label migrated resources with MigMigration UUID.

-  To start a MigPlan rollback, user will create a _new_ MigMigration CR with `spec.rollback: true` pointing at the appropriate MigPlan to roll back. This will ensure that rollback itinerary can't be switched to in the middle of another itinerary since MigMigration CR execution is ordered, one at a time. 

- Make sure that on creation, a MigMigration will immediately enter `RollbackItinerary` if `spec.rollback` is true.

---

@jortel if you want to add on feel free. @aufi if you have questions we can get together and discuss these.

**Comment by djwhatle** [comment]
@jwmatthews is it a requirement to provide the user with a option to auto-rollback on failure, or is it sufficient to give the user manual control over when rollback runs per migplan?

**Comment by aufi** [comment]
Adding notes on current status, restored objects labeling has been updated (https://github.com/konveyor/openshift-velero-plugin/pull/58) and I'm now debugging deleteRestores step https://github.com/konveyor/mig-controller/blob/master/pkg/controller/migmigration/restore.go#L243

## deleteRestores
My update with migplan-based restores query doesn't work well (seems to find the migmigration instead of restored objects) and this needs to be resolved.

## (Un)Quiesce
Looks well from my point of view. Current implementation uses annotations created on actual objects during migration run, any migration link doesn't seem to be used there https://github.com/konveyor/mig-controller/blob/master/pkg/controller/migmigration/quiesce.go#L161-L228

**Comment by aufi** [comment]
Current PRs are able rollback migrated application, initial demo: https://youtu.be/T1hAY9ObAG0
