### ISSUE TITLE
MigPlan: Validation should check whether registry pods are healthy 

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/mig-controller#678]
**Describe the bug**
I had CAM 1.2.4 installed on my source cluster. I upgraded to 1.2.5 by only deleting the migration operator pod, and left the metadata untouched in the operator deployment. The `REGISTRY_IMAGE` value was set to an older image tag which is no longer available in RH container catalog. As a result, after creation of migplan, the registry pods did not come up and were stuck in `ImagePullBackOff`. However, that didn't stop MigPlan from becoming `Ready`. Unaware of the issue, I created a migmigration and it failed at `InitialBackupFailed` phase reporting `PartiallyFailed` error on the backup object. There were no obvious errors in the Velero log. It took me significant amount of time to reach to the actual cause of the issue. 

**To Reproduce**
You can simulate the failure by deliberately setting REGISTRY_IMAGE value to something non-existent. 

1. Edit mig-operator deployment on the source cluster, and set environment variable MIGRATION_REGISTRY_TAG to `0ae610db4f73b6a5353c4821165bd60a8c4e86ac5ba5f1d60cd532f5bcd814bd` 
2. Run a migration.

**Expected behavior**
I'd expect either of these two behaviours to happen: 
1. MigPlan validation fails and the plan shows `NotReady` condition
2. OpenShift velero plugin handles this failure more gracefully and shows a relevant error message in the status or logs

**Comment by alaypatel07** [comment]
@pranavgaikwad I think this plays into the work with the registry readiness/health check @shubham-pampattiwar and I are looking into this sprint

**Comment by djwhatle** [comment]
This has been fixed.
