### ISSUE TITLE
Migcluster is getting ready state only in insecure mode

### ISSUE THREAD

**Issue by ashoks27** [konveyor/mig-controller#682]
**Describe the bug**
I am running a OCP4.4 cluster in IBM cloud and am planning to migrate apps from 3.11 to 4.4 . The MigMigration is not getting ready unless we use the option Insecure True in spec of the migcluster.  Please let us know whether the reason for it and issues in using this flag.

**To Reproduce**
Name:         migcluster-remote
Namespace:    openshift-migration
Labels:       controller-tools.k8s.io=1.0
Annotations:  openshift.io/touch: 7f91d5bd-fce8-11ea-a9b1-a24a599b435c
API Version:  migration.openshift.io/v1alpha1
Kind:         MigCluster
Metadata:
  Creation Timestamp:  2020-09-17T09:30:46Z
  Generation:          10
  Resource Version:    27318345
  Self Link:           /apis/migration.openshift.io/v1alpha1/namespaces/openshift-migration/migclusters/migcluster-remote
  UID:                 95e18767-2add-47a8-a4b2-4201f131106e
Spec:
  Insecure:         true
  Is Host Cluster:  false
  Service Account Secret Ref:
    Name:       sa-token-remote
    Namespace:  openshift-migration
  Storage Classes:
    Access Modes:
      ReadWriteOnce
    Default:      true
    Name:         managed-nfs-storage
    Provisioner:  XXXXXX/nfs
  URL:            https://XXXXXXXXXX:8443/
Status:
  Conditions:
    Category:              Required
    Last Transition Time:  2020-09-22T12:52:22Z
    Message:               The cluster is ready.
    Status:                True
    Type:                  Ready
  Observed Digest:         ab5683ec607b9b6241c21678490e64c41bef77a59f9b213a638a5e0add4ba61c
Events:                    <none>
[root@oc4377604745 ~]# 

**Expected behavior**
The Cluster status should be available without mentioning Insecure option

**Comment by ashoks27** [comment]
Adding to the above , below attached is the error which we got while we didn't mention insecure option.  Please let me know if you need any further details. Thanks.

root@oc8660015353 ~]# oc -n openshift-migration describe migcluster migcluster-remote
Name:         migcluster-remote
Namespace:    openshift-migration
Labels:       controller-tools.k8s.io=1.0
Annotations:  openshift.io/touch: c0d56278-f8bb-11ea-a9b1-a24a599b435c
API Version:  migration.openshift.io/v1alpha1
Kind:         MigCluster
Metadata:
  Creation Timestamp:  2020-09-17T07:59:45Z
  Generation:          2
  Resource Version:    23925473
  Self Link:           /apis/migration.openshift.io/v1alpha1/namespaces/openshift-migration/migclusters/migcluster-remote
  UID:                 28440e9f-73a8-4a9c-a3a3-7428f3c87a6f
Spec:
  Is Host Cluster:  false
  Service Account Secret Ref:
    Name:       sa-token-remote
    Namespace:  openshift-migration
  URL:          https://xx.xx.xx.xx:8443
Status:
  Conditions:
    Category:              Critical
    Last Transition Time:  2020-09-17T07:59:46Z
    Message:               Test connect failed: Get "https://xx.xx.xx.xx:8443/api?timeout=5s": x509: certificate signed by unknown authority
    Reason:                ConnectFailed
    Status:                True
    Type:                  TestConnectFailed
  Observed Digest:         a65b913a85cbd51881ff0bd2efb25792ba458932e31457376f9806e75b333d94
Events:                    <none>
[root@oc8660015353 ~]#

**Comment by djwhatle** [comment]
Hi @ashoks27! You can configure your MigCluster to connect in "secure" mode by supplying an appropriate CABundle. 

Using `MigCluster.spec.insecure: true` will still encrypt traffic between clusters, but due to the missing CABundle we can't verify that the remote cluster has an authentic signed TLS (SSL) certificate.

---

- _Option 1:_ If you set up your MigCluster from the Web UI, there will be an option to supply a CABundle in the MigCluster editing modal. The Web UI will automatically base64 encode your CABundle.

![image](https://user-images.githubusercontent.com/7576968/94047568-44421e80-fda0-11ea-8f84-381ee54a8439.png)


- _Option 2:_ If you set up your MigCluster from the CLI, you can add your _base64 encoded_ CABundle to the `MigCluster.spec.caBundle` field. 

```
# Generating a base64 representation of your caBundle
echo -n "<your-cabundle-goes-here>" | base64 -w 0

PHlvdXItY2FidW5kbGUtZ29lcy1oZXJlPg==
```

**Comment by djwhatle** [comment]
@ashoks27 I've created an [additional validation checking for caBundle presence](https://github.com/konveyor/mig-controller/pull/689) to help expose the reason for this type of failure for future users encountering the problem.

**Comment by djwhatle** [comment]
This issue closed due to the respective PR merging, but please feel free to re-open it if you have followup questions.

**Comment by ashoks27** [comment]
Hello @djwhatle ,

Thanks a lot for your information on CAbundle and Insecure option. Currently we can try only CAM CLI option as we have some issue with CAM UI in our cluster. Would you please help in providing the instructions to configuring the CAbundle.

**Comment by djwhatle** [comment]
@ashoks27 CLI instructions are as follows:

1. Obtain a copy of the CA bundle that was used to sign the TLS cert for the remote cluster APIserver. 

2. Generate a base64 representation of the CA bundle

```bash
cat your-ca-bundle-filepath | base64

[... base64 output will appear here ...]
```

3. Plug the generated base64 CA bundle representation into your MigClusters spec.caBundle.

```
oc edit migcluster your-remote-cluster
```

```
  spec:                                                                            
    caBundle: PHlvdXItY2FidW5kbGUtZ29lcy1oZXJlPg==                                 
    [...]
```
