### ISSUE TITLE
My customer do not want the route name to change to new domain.

### ISSUE THREAD

**Issue by ericnie2015** [konveyor/mig-controller#684]
sorry ,should be route url in the topic.

Dear experts:

I have a customer using ocp 3.11 and in one cluster, they use some custom domain name in the route url (not one ,but serverl different url) , but when they migrate the application to OCP 4.5, they find all of the service route url change to new domain name,like apps.ocp4..... , I knew that is the migration tools want the route can succefully acesse, but their requirement is can we have a option that can keep the route url as the same as the ocp 3.11 and not migrate to a new one?
so that make the customer feeling the same as using old one.

Thanks.

**Comment by sseago** [comment]
@dymurray I thought we were only changing the route names with cluster-managed route paths, and static/custom ones were *not* being changed. Is this still the case?

**Comment by ericnie2015** [comment]
if that is true ,that is great, I will check tomorrow and give your a reply, Thank you!

**Comment by jwmatthews** [comment]
Assume below is controlling this, so the "openshift.io/host.generated" controls if we reset the hostname or not.
Would assume if 'openshift.io/host.generated' is missing or set to false, we wouldn't update the hostname

https://github.com/konveyor/openshift-velero-plugin/blob/master/velero-plugins/route/restore.go#L31


```
hostGenerated := route.Annotations["openshift.io/host.generated"]
	if hostGenerated == "true" {
		p.Log.Info("[route-restore] Stripping src cluster host from Route")
		route.Spec.Host = ""

		var out map[string]interface{}
		objrec, _ := json.Marshal(route)
		json.Unmarshal(objrec, &out)

		return velero.NewRestoreItemActionExecuteOutput(&unstructured.Unstructured{Object: out}), nil
	}
```

**Comment by ericnie2015** [comment]
ok, thanks a lot! I will try tomorrow.

**Comment by ericnie2015** [comment]
I confirm that is only changed the route have annotation openshift.io/host.generated, so that is perfect!

**Comment by jwmatthews** [comment]
@ericnie2015 from last comment I assume we are good to close this issue, if you have any other questions please let us know and we can reopen.
