### ISSUE TITLE
Pending `openshift-migration` Backups, Restores, PVBs and PVRs should be removed at migration start

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#703]
**Is your feature request related to a problem? Please describe.**

Failed migrations can leave behind Velero resources in _pending_ state:

- Backups
- Restores
- PodVolumeBackups (PVBs)
- PodVolumeRestores (PVRs)

Sometimes, these leftover Velero resources will result in Velero and Restic controllers being "locked up" and unable to respond to new requested actions from a newer migration attempt. 

**Describe the solution you'd like**

 1. Remove any _pending_ Backups, Restores, PVBs, PVRs in the `openshift-migration` namespace at the beginning of each migration attempt
 2. Possibly run a `DeleteBackupRequest` to remove pending backup if needed
3. If anything was removed in (1.) or (2.), bounce the corresponding appropriate Velero or Restic controller pods to _unlock_ them
4. Wait for Velero / Restic controller to re-gain readiness before continuing

**Describe alternatives you've considered**
A more elegant solution to the above would be to implement a "cancel" feature on all of the above mentioned Velero kinds so that we could gracefully stop pending tasks. @sseago are you aware of the work being done on this upstream?

cc @alaypatel07 @dymurray @pranavgaikwad

**Comment by djwhatle** [comment]
Picking this up today.

**Comment by sseago** [comment]
@djwhatle Won't backups/restores that are queued up from other running migrations also be 'Pending'? I think we'd only want to delete pending ones if they belong to Failed (or at least Completed) MigMigrations. Also, since we may eventually be sharing velero with OADP use, a non-MTC pending migration probably shouldn't be touched by MTC if it's waiting on a migration or something (rather than pending because velero is hung somehow).

**Comment by djwhatle** [comment]
@sseago 

> Won't backups/restores that are queued up from other running migrations also be 'Pending'? 
Yes. I don't think it should be permissible to run multiple migrations at once though. This came up in the last scrum of scrums, wrote this up: https://github.com/konveyor/mig-controller/issues/733

> Also, since we may eventually be sharing velero with OADP use, a non-MTC pending migration probably shouldn't be touched by MTC if it's waiting on a migration or something (rather than pending because velero is hung somehow).

This makes sense to me as something we should look out for. I can filter the CRs we delete to only ones with Mig* correlation labels attached. Will update linked PR.

**Comment by sseago** [comment]
@djwhatle So the "prevent 2 migmigrations" plan feels like a workaround. If the credentials problem in velero is solved, for example, then two users ought to both be able to click "migrate". The fact that velero works serially shouldn't prevent migration 2 from starting backup after migration1 is done with the backup phase. I understand why, in the short term, we may want to prevent that, but I don't think we should assume that this workaround is permanent when we write things like cleanup code. I think we still probably only want to delete velero CRs if they belong to completed/failed/canceled migmigrations. Ignore them if we can't identify the migmigration or they don't have one.

**Comment by djwhatle** [comment]
@sseago I modified the linked PR to meet the spec we discussed earlier today. Please take another look when you have a moment.
