### ISSUE TITLE
list the unsuspended failed plans on registryHealth watch provider

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/mig-controller#708]
**Is your feature request related to a problem? Please describe.**

yes it is a problem

With #681 we will list all the failed plans in registryHealth watch provider.

**Describe the solution you'd like**

We can enhance that by filtering the list with just a suspended plan. Also, consider adding the failed label for non-closed, non-suspended plans.

**Comment by djwhatle** [comment]
Resolved by #717
