### ISSUE TITLE
Bug 1896015: Discovery Service requires restart to get latest changes to Plan Tree view

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#724]
See: https://bugzilla.redhat.com/show_bug.cgi?id=1896015

**Describe the bug**
I ran a few migrations against a single MigPlan while working on #723 . I found that the PodVolumeRestores and PodVolumeBackups will sometimes only show up in the plan tree view if you kill mig-controller, which also kills the discovery service, and let it restart.

The PodVolumeRestores and PodVolumeBackups are also  missing from JSON output of /plan/tree.

**What I expected**
![image](https://user-images.githubusercontent.com/7576968/97611739-f0ed6c80-19ec-11eb-8b59-975f00c82239.png)

**What I saw**
Same as above, but with PodVolumeBackups and PodVolumeRestores missing until I restarted the controller.

**To Reproduce**
1. Run a few migrations against the same MigPlan
2. Check the debug tree view in the UI
3. Notice that the output received from the discovery service is missing PodVolumeBackups that are present on the cluster

**Comment by jortel** [comment]
I will try to reproduce and investigate next week.

**Comment by jwmatthews** [comment]
I saw similar behavior when preparing MTC labs with MTC 1.3.1.  

I consistently failed to see any PVB/PVR data in my debug views. 

I was using a stock MTC 1.3.1 install from production.
