### ISSUE TITLE
proposed fix for health check of stage pods

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/mig-controller#726]
**Describe the bug**

We need to check for the health of stage pods during restore in a way that does not fail the Restore operation.

**Proposed Solution**

1. While waiting for velero restore to complete, list all the stage pods in the destination
2. Compare the list of stage pods on destination with the list of stage pods in the source. If any missing, report in the message for the condition of this phase
3. Iterate over the list of stage pods on the destination and check the containers of each stage pods are Ready. If not report the list of unhealthy stage pods in the message condition for this phase
4. If all stage pods are available on destination and healthy, report message, "waiting for restore to complete"

**Comment by djwhatle** [comment]
@alaypatel07 to be clear, if stage pods are missing, does this raise a non-blocking warning that will be displayed in the message field?

**Comment by alaypatel07** [comment]
good question.

I think if stage pods are missing and velero restore is completed, it either means:
1. The restore succeeded and velero snapshotted it rather than copying with restic
2. The restore failed, hitting the restic timeout

In either of these cases, we would want to fail the migration so a user can take further actions on that.

If the migration is running and stage pods are missing we really cannot predict deterministically whether it's an error of its just waiting for velero to do the restore, hence, it will be a non-blocking message in the `Running` condition.

@djwhatle @sseago let me know if I am missing anything here

**Comment by alaypatel07** [comment]
fixed by #747
