### ISSUE TITLE
[MIG-351] PartialFailures should mark migration "complete with warning" instead of complete failure

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-controller#729]
Today a "PartialFailure" that occurs in Velero marks the entire a complete
failure, despite the fact that entire classes of partial failures could be
acceptable to a user. As a first phase towards improving our partial failure
experience, these should be reported as a warning similar to the way that
restic restore errors are considered warnings.

**Comment by alaypatel07** [comment]
Completed via #760
