### ISSUE TITLE
Progress reporting for rsync client pod

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/mig-controller#730]
**Is your feature request related to a problem? Please describe.**
For the new DirectVolumeMigration Controller, we need the ability to report the progress of the migration operation. At the very minimum, we want to report something like:

- 3/10 rsync client pods are running
- 4/10 rsync clients pods have completed
- 3/10 rsync clients pods have failed

For more granular reporting we want to get logs from the source client pods and get the actual rsync progress. 

**Describe the solution you'd like**

- Phase 1: Add a new CR that will

1. poll every 5 seconds to get the pod
2. report whether the pod is running, completed, or failed.

- Phase 2: If the pod is running, stream updates from the client rsync pod logs in the status.

**Describe alternatives you've considered**

Running the poll in the wait step of DirectVolumeMigration controller phase.

This was rejected because it will complicate the Phase logic. All it really cares about is to wait on the status of each client pod. Hence having an abstraction object in the same cluster as the controller would allow this controller to watch that new object and hide the implementation detail of polling under the new object controller

**Additional context**

**Comment by djwhatle** [comment]
@alaypatel07 I'm trying to understand the value addition that the `Phase 1` approach has compared to just monitoring the Pod directly.

Please correct me if I'm misinterpreting what you've wrote in my question below.


> Phase 1: Add a new CR that will
> poll every 5 seconds to get the pod
> report whether the pod is running, completed, or failed.

1. The Pod itself should be able to display the running/completed/failed information directly, right? Why introduce another layer?

2. Is the CR you're proposing we introduce going to monitor >1 rsync pods, collecting all of the progress into one place, or is it `1:1 new CR : rsync Pod`?

**Comment by alaypatel07** [comment]
> The Pod itself should be able to display the running/completed/failed information directly, right? Why introduce another layer?

The pod is always deployed on the source side, we don't have a watch mechanism there. We need to poll. Phase 1 logic is just running/completed/failed information based on pod, but phase 2 has complexity where we need to parse the logs and provide progress back. In order to keep the complexity out of the phase where we are waiting for the pods to completed adding this CR is valuable. Also, since this CR is a representation of the Pod in the controller cluster, we get "watch" for free on it, and the poll is an implementation detail hidden under the new controller.

> Is the CR you're proposing we introduce going to monitor >1 rsync pods, collecting all of the progress into one place, or is it 1:1 new CR : rsync Pod?

I am proposing 1:1 new CR: rsync Pod.

**Comment by djwhatle** [comment]
When a migration is running, the `migmigration` controller polls for latest migration state every 3 seconds. 

I don't think it's beneficial for us to run the `migmigration` reconcile at a higher frequency than 3 seconds (e.g. in this case i think it's being suggested we reconcile every time a line is logged from rsync output since that will be dumped into status).  Given that we aren't using the cached client in a bunch of places and don't want to overload the APIserver, I would think that from a performance perspective it would negatively impact us to add more watches to the `migmigration` controller compared to checking on things at a more relax interval (the 3 second poll).

On a different note: I think actually agree with you that it would be cool if we had a CR that was 1:1 with rsync and just showed the aspects we care about, visible in the status columns. I'm imagining being able to do something like:

```
oc get rsyncjobs # made up this name, ignore that

NAME         AGE  STATUS      PROGRESS  PVC
rsyncjob-1   5s   InProgress  58%       my-pvc-1
rsyncjob-2   7s   InProgress  92%       my-pvc-2
```

**Comment by alaypatel07** [comment]
@djwhatle initially the plan was to add exact progress number as you have in the example. But in order to get best value for engineering time, I suggested we start with tailing last 10 lines of the rsync output. So the interface now becomes

```
oc get dpmp foo -oyaml
...
...
...
status:
  conditions:
  -
  phase: Running
  logLines: "|
        696.25M  38%   40.64MB/s    0:00:16 (xfr#167, to-chk=9/178) 2020/10/28 02:31:39 [1] <f+++++++++ file90
        700.45M  38%   40.64MB/s    0:00:16 (xfr#168, to-chk=8/178)2020/10/28 02:31:40 [1] <f+++++++++ file91
        704.64M  38%   40.64MB/s    0:00:16 (xfr#169, to-chk=7/178)2020/10/28 02:31:40 [1] <f+++++++++ file92
        708.84M  39%   40.65MB/s    0:00:16 (xfr#170, to-chk=6/178)2020/10/28 02:31:40 [1] <f+++++++++ file93
        713.03M  39%   40.65MB/s    0:00:16 (xfr#171, to-chk=5/178)2020/10/28 02:31:40 [1] <f+++++++++ file94
        717.23M  39%   40.65MB/s    0:00:16 (xfr#172, to-chk=4/178)2020/10/28 02:31:40 [1] <f+++++++++ file95
        721.42M  39%   40.65MB/s    0:00:16 (xfr#173, to-chk=3/178)2020/10/28 02:31:40 [1] <f+++++++++ file96
        725.61M  40%   40.66MB/s    0:00:17 (xfr#174, to-chk=2/178)2020/10/28 02:31:40 [1] <f+++++++++ file97
        729.81M  40%   40.66MB/s    0:00:17 (xfr#175, to-chk=1/178)2020/10/28 02:31:40 [1] <f+++++++++ file98
        734.00M  40%   40.67MB/s    0:00:17 (xfr#176, to-chk=0/178)2020/10/28 02:31:40 [1] <f+++++++++ file99"
```

**Comment by alaypatel07** [comment]
The thought process is, we want to add visibility into rsync but at the same time keep sanity in our code base. Parsing logs will get more and more complex in production as we get into edge cases of all that rsync can log. 

I asked myself, is parsing really adding value? (It would be really COOL but) Can we add value in an easier more reliable way? 

Let me know if you have any suggestions

**Comment by alaypatel07** [comment]
That said, in further iteration, we can always add the parsing logic that would give a number on the progress, if available in the last 10 lines. My preliminary investigation shows what the 40% complete in the above snippet only shows the update of files that were uploaded, it does not take into account the files that were deleted. Hence, I think in order to organically grow I am trying to make it work so we have logs available, and then once we have basic plumbing in place we can access how to get progress number

**Comment by djwhatle** [comment]
@alaypatel07 I may be missing some other features, but I don't see much value in a CR that just displays the last 10 lines of a Pod log. This is provided by the k8s Pods directly with `oc logs pod_name --tail=10`

If there is more intelligence in the progress CR, then it starts to make sense to me.

I don't think parsing the progress should be too bad. I put together a demo that grabs the last percent and transfer rate logged in this demo: https://play.golang.org/p/iMbCcYispAf

```
package main

import (
	"fmt"
	"regexp"
)

func main() {
	// Example of parsing rsync output for progress percent and transfer rate
	last10 := `696.25M  38%   40.64MB/s    0:00:16 (xfr#167, to-chk=9/178) 2020/10/28 02:31:39 [1] <f+++++++++ file90
        700.45M  38%   40.64MB/s    0:00:16 (xfr#168, to-chk=8/178)2020/10/28 02:31:40 [1] <f+++++++++ file91
        704.64M  38%   40.64MB/s    0:00:16 (xfr#169, to-chk=7/178)2020/10/28 02:31:40 [1] <f+++++++++ file92
        708.84M  39%   40.65MB/s    0:00:16 (xfr#170, to-chk=6/178)2020/10/28 02:31:40 [1] <f+++++++++ file93
        713.03M  39%   40.65MB/s    0:00:16 (xfr#171, to-chk=5/178)2020/10/28 02:31:40 [1] <f+++++++++ file94
        717.23M  39%   40.65MB/s    0:00:16 (xfr#172, to-chk=4/178)2020/10/28 02:31:40 [1] <f+++++++++ file95
        721.42M  39%   40.65MB/s    0:00:16 (xfr#173, to-chk=3/178)2020/10/28 02:31:40 [1] <f+++++++++ file96
        725.61M  40%   40.66MB/s    0:00:17 (xfr#174, to-chk=2/178)2020/10/28 02:31:40 [1] <f+++++++++ file97
        729.81M  40%   40.66MB/s    0:00:17 (xfr#175, to-chk=1/178)2020/10/28 02:31:40 [1] <f+++++++++ file98
        734.00M  40%   40.67MB/s    0:00:17 (xfr#176, to-chk=0/178)2020/10/28 02:31:40 [1] <f+++++++++ file99\`

	// Percent Complete
	percentRegex := regexp.MustCompile(`\d+\%`)
	percentMatches := percentRegex.FindAllString(last10, -1)
	
	// Transfer Rate
	rateRegex := regexp.MustCompile(`\d+\.\w*\/s`)
	rateMatches := rateRegex.FindAllString(last10, -1)
		
	if len(percentMatches) > 0 && len(rateMatches) > 0 {
		progressPercent := percentMatches[len(percentMatches)-1]
		transferRate := rateMatches[len(rateMatches)-1]
		fmt.Printf("Progress: [%v], Transfer Rate: [%v]", progressPercent, transferRate)
	}
}
```

**Comment by alaypatel07** [comment]
> @alaypatel07 I may be missing some other features, but I don't see much value in a CR that just displays the last 10 lines of a Pod log. This is provided by the k8s Pods directly with oc logs pod_name --tail=10

I think the value comes from the fact that this CR would be the basis of other developments we do for progress reporting. It abstracts the complexity from the DirectVolumeMigration controller, and we have all the implementation detail nicely wrapped in this controller. Apart from that engineering benefit, +1 users get to see the remote cluster logs from the controller cluster as well.

For an example of the implementation details: in order to grab the logs like `oc logs pod_name --tail=10` we need to establish a bi-directional communication underneath the hood. In order for efficient implementation, we would want to always use a common socket for the same pod and not set up a new connection every time we reconcile. These kinds of details are nicely orchestrated if we have a separate controller compared to implementing them Itinerary tasks of the DirectVolumeMigration controller.

Thanks for the demo playground link, will be useful.
