### ISSUE TITLE
Fix noisy "unsupported event type" message 

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#750]
**Describe the bug**

After recent round of event logging changes, seeing this a lot coming out of mig-controller. 
```
E1106 14:49:11.692555       1 event.go:264] Unsupported event type: ''
```

**Comment by shubham-pampattiwar** [comment]
@djwhatle this is caused if the `Reason` field is not set for a given `Condition` , i.e. we need `Reason` field set for all the `Condition(s)` we are logging, essentially for all the `SetCondition` calls. I have taken this into consideration and added the missing `Reason` fields in the PRs raised after the `migstorage_controller` and `migcluster_controller`, once those PRs are merged, this issue should be fixed.

**Comment by djwhatle** [comment]
Nice, I'll link those PRs then. Thanks @shubham-pampattiwar

**Comment by alaypatel07** [comment]
Team, this should go away, please feel to re-open if it still persists
