### ISSUE TITLE
Progress pipeline does not show info when `CancelItinerary` is running

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#769]
**Describe the bug**
I was testing #768 and noticed that while running the `CancelItinerary`, the pipeline no longer shows detailed progress info / descriptions. I think we should give more thought on how to handle `CancelItinerary` and `FailedItinerary` within the progress reporting system.

**To Reproduce**
1. Run a migration
2. Cancel the in-progress migration using the mig-ui `Cancel` button 
3. Watching the migmigration CR, notice the pipeline doesn't update.

**Comment by pranavgaikwad** [comment]
Pipeline does update when Cancel itinerary runs, however the previous step is not marked completed.
