### ISSUE TITLE
[MIG-284] Validation to verify networking environment is suitable for DVM/DIM use case

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#780]
Upon migplan creation, we want to perform some basic validation check to confirm that if the user has selected Direct migration that the migration won't totally fail.

** Release 1.4.0**
- [ ] Document a way to deploy, test, and verify a direct migration is possible from 3.11->4.6 using service catalog application
- [ ] Support validation of exposed registry route for migclusters

** Release 1.4.z**
- [ ] Design document for preflight validation integration with DVM/DIM
- [ ] Implement preflight validation direct migration requirements are satisfied

**Comment by sseago** [comment]
The goal here is to attempt to perform an actual PV and image copy with some small test volume and image. One possible approach would be a new task phase for this, which could be incorporated as an optional step at the beginning of a migration, or even as a standalone "validate" itinerary, which would be launched by creating a migmigration with `validateOnly=true` or something similar.

**Comment by dymurray** [comment]
For docker-registry svcs with v2 support, we can validate the route is valid by checking `/v2/` endpoint with a valid token and confirm it returns a 200.

```
$ curl -k https://docker-registry-default.apps.dymurray-ocp3.mg.dog8code.com/v2/ -H "Authorization: bearer UCbSDHG4n4riixjkBHvWP9GTCuAvNIl_CbigKg4fJno"
{}
```

We will want to fail migcluster validation if we do not get a 200 response from this endpoint.

**Comment by djwhatle** [comment]
@dymurray is this for release-1.4.0, or release-1.4.z? I see both labels assigned.
