### ISSUE TITLE
mig-controller should allow rollback to start after final migration is complete

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#807]
**Describe the bug**
Currently, if a final migration is complete, a new `Rollback` MigMigration will not run

**To Reproduce**
1. Run a migration to completion
2. Attempt rollback. You can create the new MigMigration CR with spec.rollback=true, but it won't run

**Comment by sseago** [comment]
Ahh, this is probably the code we added to prevent migrations from running when there's a final migration that completed.

**Comment by djwhatle** [comment]
@sseago right, I'm going to need to modify this in some way that doesn't break existing behavior + doesn't break what the UI is expecting.

**Comment by djwhatle** [comment]
@sseago I forgot what the actual behavior was. @aufi already handled this in the rollback code. Just needed a UI change. Will  be resolved by https://github.com/konveyor/mig-ui/pull/1071
