### ISSUE TITLE
[MIG-542] Improve dvm controller design for more resiliency

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/mig-controller#823]
**Is your feature request related to a problem? Please describe.**

The DVM controller has some room for improvement in being more resilient to failures. For example if the dvm fails due to stale certs or destination transfer pods missing, we want the controller to know this and repair it. May be we want the controller to have a concept of retries, but that's an implementation detail.

**Describe the solution you'd like**
For 1.4.0, I would like us to come up with a doc describing our plan for making the dvm controller more resilient to known failure cases.

**Comment by eriknelson** [comment]
DVM retry has been merged to master and we expect to release with mtc-1.4.3
