### ISSUE TITLE
[MIG-284] DVM fails on RWO volumes if pods aren't scheduled on the same node

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-controller#834]
For some storage providers, RWO volumes *must* be mounted by pods that are scheduled on the same node. For stage pod workflow we did this by copying the original application pod's affinity values and applying them to the stage pod we create for that volume.

However, in the DVM case we operate on a per-pvc basis without any knowledge of the application pod itself. It's possible for the rsync client pod to be scheduled on a node different from the app pod as seen below:
```
$ oc get pods directvolumemigration-rsync-transfer-mysql -o yaml |grep -i nodeName
  nodeName: ip-172-18-8-191.ec2.internal
$ oc get pods mysql-1-kq8xc -o yaml |grep -i nodeName
  nodeName: ip-172-18-6-152.ec2.internal
```

We need to update DVM to check if a PVC is being used by a running pod and copy that pods affinity and/or node name to be used when scheduling the rsync client pod.

**Comment by sseago** [comment]
Implementation suggestion:
As a one-time step before creating any pods, iterate over *running* pods (in each namespace), any pods that have PVCs, create a mapping from PVC namespaced name to nodeName, then when creating src transfer pods, set nodeName based on the map.
￼`transferPod.NodeName = pvcNodeMap[pvcNamespacedName]`
￼

**Comment by dymurray** [comment]
Ahh thanks Scott, actually makes things easier.
