### ISSUE TITLE
[MIG-284] Missing phase descriptions in DVM

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/mig-controller#838]
**Describe the bug**
Related to #820 

Following phases in DVM controller are missing descriptions :

>     CleanStaleRsyncResources
>     WaitForRsyncResourcesTerminated
>     WaitForStaleRsyncResourcesTerminated
>     Verification
>     CreateStunnelPodOnSource
>     EnsureStunnelPodOnSourceHealthy

**Expected behavior**
Phases should have descriptions

**Comment by eriknelson** [comment]
@pranavgaikwad @alaypatel07 Is this currently in progress, or has been completed?

**Comment by alaypatel07** [comment]
@eriknelson not completed, just got to know this is an issue, will pick it up this sprint
