### ISSUE TITLE
configure rsyncd with logs

### ISSUE THREAD

**Issue by alaypatel07** [konveyor/mig-controller#843]
**Describe the bug**
The DVM controller creates a rsync daemon pod on the destination cluster. The rsync daemon pod does not have logging enabled currently. 

**To Reproduce**
1. Create a DVM CR. 
2. Run command 'oc logs -f <transferpod> -c rsyncd'
3. It prints nothing

**Expected behavior**
I expect the rsyncd daemon to be deployed logs to be helpful in debugging in case rsync operation is not successful.

**Additional context**
Steps:
1. the rsyncd config should have logging enabled https://gist.github.com/alaypatel07/573074f5717570221c872f03f3ef7ecc#file-create-destination-pod-sh-L22
2. the rsyncd pod should be mounted with a volume that it can write to
3. the rsync pod logs should be redirected to file in step 2 for oc logs -f to work

**Comment by alaypatel07** [comment]
cc @eriknelson @dymurray

**Comment by pranavgaikwad** [comment]
Fixed through https://github.com/konveyor/mig-controller/pull/894
