### ISSUE TITLE
DVM: Check status of current phase before returning "true" to move to next phase 

### ISSUE THREAD

**Issue by JaydipGabani** [konveyor/mig-controller#875]
The DVM controller returns `true` in some edge cases where returning `true` is not the correct approach. For instance [here](https://github.com/konveyor/mig-controller/blob/c7801d91c2c4e70b6ba2b73d8bffcd83da46ee36/pkg/controller/directvolumemigration/stunnel.go#L493), the function `areStunnelClientPodsRunning` will return `true` even if there are 0 stunnel pods running. 

**Expected behavior**
In such cases, the DVM controller should put up a warning depicting the expected behavior (in the above example, it should warn that there are no stunnel pods running instead of returning `true`) 

**Instances found**

https://github.com/konveyor/mig-controller/blob/master/pkg/controller/directvolumemigration/namespace.go#L24 (Can be discarded)
https://github.com/konveyor/mig-controller/blob/master/pkg/controller/directvolumemigration/rsync.go#L72
https://github.com/konveyor/mig-controller/blob/master/pkg/controller/directvolumemigration/stunnel.go#L493

**Comment by alaypatel07** [comment]
Thanks for the issue @JaydipGabani 

I think the core problem is:

The dvm controller is full of a pattern where we do the following:

1. get the list of resources
2. range through the list of returned resource and check whether the state is valid or not

What we miss in this pattern is comparing whether the list returned the expected number of items. I propose we go through the codebase and modify the pattern to the following:

1. get the list of resources
2. check if the number of items returned is as expected. If not wait for some time and raise a warning of fail depending on how severe it is
3. check each item's state

I think the above will solve the problems of list returning empty or list returning fewer resources than expected.
