### ISSUE TITLE
When cleaning up DeploymentConfigs, rollback can get stuck waiting on PVCs to terminate. 

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#998]
**Describe the bug**
Rollback can get stuck waiting on PVCs to terminate. PVCs are waiting for a Completed Pod (0 replicas) to be deleted. The completed `deployer` Pod does not have our `migrated-by-migplan: xyz` label because it was created by a DeploymentConfig.  The DeploymentConfig doesn't completely clean these Pods up when the DC is deleted, and provides no way to attach custom labels to the deployer/hooks Pod it creates.

**To Reproduce**
1. Migrate rocket-chat 
2. Attempt rollback
3. See rollback sit forever "Deleting PVC" but the PVC not deleting because it has a finalizer on a Pod that doesn't have our `migrated-by` label.

**Expected behavior**
Pods are deleted and PVCs are not stuck waiting for deletion. I think we could solve this by injecting the `migrated-by` label into Pod templates with our plugin.

**Comment by djwhatle** [comment]
After further investigation, there's no way to pass a label to the deployer pod through a pod template. We may need a one-off deletion routine for DeploymentConfigs since they have kind of weird behavior.

**Comment by sseago** [comment]
@djwhatle Wouldn't the same thing happen with any resource type with a pod template? Deployment, Job, CronJob, DaemonSet, etc.?

**Comment by djwhatle** [comment]
@sseago in this case, it's not the Pod template that is leftover. There is a `deployer` Pod unique to DeploymentConfigs that isn't lifecycle managed by the DeploymentConfig controller (it doesn't get cleaned up upon DC deletion). I believe this is a unique problem with DCs.
